### ISSUE TITLE
Training different policy didn't work

### ISSUE THREAD

**Issue by mincheulkim** [ChanganVR/RelationalGraphLearning#10]
Hi, for training different policy(e.g. sarl, cadrl), just adding the argument in command line: "--policy rgl/sarl/orca" didn't work.

Because the config.py from /icra_benchmark/mp_seperate.py dominate whole code, above added argument don't work.

To solve the issue, another argument need to be added: "--config rgl/sarl.py"

**Comment by ChanganVR** [comment]
That's right, I believe the default configuration is mp_separate.py and you need to change the configs if you want to train other policies.
