### ISSUE TITLE
Train with real human trajectory

### ISSUE THREAD

**Issue by mincheulkim** [ChanganVR/RelationalGraphLearning#11]
Hi, Changan, thank you very much for your kind comment last time. Your advice has been of great help to my research.
My question is, can I utilize real human trajectory database in your simulations (e.g. ETH, UCY)? Previous codes included GrandCentral.py, realsim_utils, etc.

Thanks,

**Comment by ChanganVR** [comment]
Hi @mincheulkim, we tried to do that when we were doing this work but didn't finish it due to the time constraint. I believe it is definitely doable. It's just that we are not maintaining these codes and so you'll need to revise and debug them if you want to use them.
