### ISSUE TITLE
How to run LM-SARL-Linear

### ISSUE THREAD

**Issue by touranisatyajit** [ChanganVR/RelationalGraphLearning#21]
Hi,

In the paper you have mentioned that you have replaced the unrealistic assumption of access to the next ground truth state
with a linear motion model for LM-SARL-Linear. Could you please tell me what is the command I need to train this particular policy or can you please provide the model file if possible?

Thanks

**Comment by ChanganVR** [comment]
Hi there,

Please check out this model file: https://github.com/ChanganVR/RelationalGraphLearning/blob/8e87aa5ed8221efd688f8e6857ba4c38637bf6e1/crowd_nav/policy/sarl.py#L76. The `with_om` option is adding the map as input.

**Comment by touranisatyajit** [comment]
Thank you for your response!
