### ISSUE TITLE
Training different policys

### ISSUE THREAD

**Issue by liangjiaxuan1018** [ChanganVR/RelationalGraphLearning#3]
Hello, I tried to reproduce your paper, but in the first step of training different policys, I got the same training results, the same success rate, collision rate and so on. I also tried to change the default parameters of the paper, but the results didn't change either, so I wanted to know what was going on.
Thank you

**Comment by ChanganVR** [comment]
Hi, sorry for the late reply. Did you change the policy name in train.py? 

By default, it uses model_predictive_rl, but you can change it by adding the argument in command line: "--policy rgl(sarl/orca)"
