### ISSUE TITLE
drawing issue

### ISSUE THREAD

**Issue by Lyy369** [ChanganVR/RelationalGraphLearning#9]
Sorry to bother you. Could you please teach me how to draw a picture like this？

![image](https://user-images.githubusercontent.com/76517302/116566257-2f7ec800-a939-11eb-90e9-913b4e3b66e5.png)

**Comment by Lyy369** [comment]
The  error  is  as  follows:
File "/home/hp/RelationalGraphLearning/crowd_sim/envs/crowd_sim.py", line 638, in plot_value_heatmap
z = np.array(self.action_values[global_step % len(self.states)][1:])
TypeError: 'NoneType' object is not subscriptable

**Comment by ChanganVR** [comment]
Hi,

It looks like the action_values list is empty due to some reasons. You can
debug by printing the value of this list at the place where it is supposed
to be updated.

Thanks,
Changan

**Comment by Lyy369** [comment]
Thank you. I  will  have a try.

**Comment by llxClover** [comment]
> Thank you. I will have a try.
Could you tell me how to resolve the questions that the picture of value heatmap?
